name: testing-522
on: workflow_dispatch
env:
  ACTIONS_STEP_DEBUG: true

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: v-gowridurgad/setup-dotnet@feature-522
        with:
          dotnet-version: '8.0.x'
