name: testing-518
on: workflow_dispatch

jobs:
  maha:
    runs-on: ubuntu-latest
    steps:
      - name: Make default unwritable
        run: |
          sudo mkdir -p /usr/share/dotnet
          sudo chmod a-w /usr/share/dotnet
      - uses: actions/setup-dotnet@v6
        env:
          HOME: /
        with:
          dotnet-version: '8.0.x'
      - name: Where did it target?
        if: always()
        run: |
          echo "DOTNET_ROOT=$DOTNET_ROOT"
          ls -la /.dotnet 2>/dev/null && echo "TARGETED /.dotnet" || echo "did not"

  
